import streamlit as st
from PIL import Image, ImageFilter, ImageDraw, ImageEnhance
import random
from streamlit_image_comparison import image_comparison

# 1. Set up the web page title and layout
st.set_page_config(page_title="What Blindness Really Looks Like", layout="wide")

# ==========================================
# INJECT CUSTOM CSS FOR ALIGNMENT & NAV
# ==========================================
st.markdown("""
<style>
/* Center the content blocks */
.centered-content {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
}

/* Force image comparison to center and reduce bottom padding */
[data-testid="stVerticalBlock"] > div:has(div.stImageComparison) {
    display: flex;
    justify-content: center;
    margin-bottom: 0px !important;
}

/* Target the specific slider component container to pull description up */
.stImageComparison {
    margin-bottom: -15px !important;
}

/* Simple Navigation Style */
.nav-bar {
    display: flex;
    justify-content: center;
    gap: 30px;
    background-color: #f0f2f6;
    padding: 15px;
    border-radius: 10px;
    margin-bottom: 25px;
    position: sticky;
    top: 0;
    z-index: 999;
}
.nav-bar a {
    text-decoration: none;
    color: #31333F;
    font-weight: bold;
    font-size: 1.1em;
}
.nav-bar a:hover {
    color: #ff4b4b;
}

img {
    max-width: 100%;
    height: auto;
}
</style>
""", unsafe_allow_html=True)

# Navigation Header
st.markdown("""
<div class='nav-bar'>
    <a href='#about-this-project-how-it-was-built'>About</a>
    <a href='#try-it-with-your-own-photo'>Uploader</a>
    <a href='#medical-eye-conditions'>Simulations</a>
</div>
""", unsafe_allow_html=True)

# Main Header Area
st.markdown("<h1 style='text-align: center;'>👁️ What Blindness Really Looks Like</h1>", unsafe_allow_html=True)

st.markdown("""
<p style='text-align: center; font-size: 1.2em;'>
    Inspired by <a href='https://www.perkins.org/what-blindness-really-looks-like/' target='_blank'>Perkins School for the Blind</a>.<br>
    Generated by Jacky Situ in Google Gemini AI.<br>
    📸 Photo Credit: <a href='https://www.pexels.com/@ganajp/' target='_blank'>Petr Ganaj</a> (Close-Up Photo of Bird Perched On Stem)
</p>
""", unsafe_allow_html=True)

st.divider()

# ==========================================
# ABOUT THE PROJECT SECTION
# ==========================================
st.header("ℹ️ About This Project & How It Was Built")

st.markdown("**🖥️ What is on this page:**")
st.write("This page features an interactive visual simulation tool. It allows users to upload their own images and use interactive sliders to compare normal vision side-by-side with six different medical eye conditions: Glaucoma, Macular Degeneration, Achromatopsia, Cataracts, Diabetic Retinopathy, and Low Vision.")

st.markdown("**🎯 Purpose:**")
st.write("This application was created to raise awareness and foster empathy. By providing a visual simulation of various medical eye conditions, it helps fully sighted individuals understand the daily visual challenges faced by those with visual impairments.")

st.markdown("**🛠️ Technologies & Libraries Used:**")
st.write("- **Streamlit:** Powers the web framework, interactive UI, and responsive layout.")
st.write("- **Pillow (PIL):** Handles background image processing, filtering, and masking.")
st.write("- **streamlit-image-comparison:** Renders the side-by-side sliding image comparisons.")

st.markdown("**🤖 Prompt Used to Generate This App:**")
st.write('Create a responsive Streamlit web app in Python using PIL to simulate blindness and eye conditions. Add side-by-side image comparison sliders, ensure images, headers, and descriptions are perfectly centered together, leave appropriate whitespace, and use full spelled-out labels. Cataract spots should be solid/blurry and Diabetic Retinopathy spots should be solid. Ensure Glaucoma is a true pinhole effect.')

st.divider()

# ==========================================
# CENTERED UPLOADER SECTION
# ==========================================
st.header("📸 Try It With Your Own Photo!")
uploader_left, uploader_center, uploader_right = st.columns([1, 2, 1])

with uploader_center:
    st.markdown("<p style='text-align: center;'>Upload a picture of your family, your living room, or a favorite place to see how it looks through the lens of these visual impairments.</p>", unsafe_allow_html=True)
    uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"], label_visibility="collapsed")

st.divider()

# ==========================================
# IMAGE PROCESSING FUNCTIONS
# ==========================================

@st.cache_data
def apply_glaucoma(img):
    mask = Image.new('L', img.size, 0)
    draw = ImageDraw.Draw(mask)
    width, height = img.size
    radius = min(width, height) // 3
    center_x, center_y = width // 2, height // 2
    draw.ellipse((center_x - radius, center_y - radius, center_x + radius, center_y + radius), fill=255)
    mask = mask.filter(ImageFilter.GaussianBlur(radius=20))
    black_img = Image.new('RGB', img.size, (0, 0, 0))
    return Image.composite(img, black_img, mask).convert("RGB")

@st.cache_data
def apply_macular_degeneration(img):
    img_copy = img.copy()
    mask = Image.new('L', img.size, 0)
    draw = ImageDraw.Draw(mask)
    width, height = img.size
    radius = min(width, height) // 4
    center_x, center_y = width // 2, height // 2
    draw.ellipse((center_x - radius, center_y - radius, center_x + radius, center_y + radius), fill=255)
    mask = mask.filter(ImageFilter.GaussianBlur(radius=20)) 
    black_img = Image.new('RGB', img.size, (0, 0, 0))
    return Image.composite(black_img, img_copy, mask).convert("RGB")

@st.cache_data
def apply_achromatopsia(img):
    return img.convert('L').convert('RGB')

@st.cache_data
def apply_low_vision(img):
    img_blur = img.filter(ImageFilter.GaussianBlur(radius=4))
    enhancer = ImageEnhance.Brightness(img_blur)
    return enhancer.enhance(0.5).convert("RGB")

@st.cache_data
def apply_cataracts(img):
    base_img = img.copy() 
    cloud_mask = Image.new('L', img.size, 0)
    draw = ImageDraw.Draw(cloud_mask)
    width, height = img.size
    random.seed(10)
    for _ in range(10): 
        x = random.randint(0, width)
        y = random.randint(0, height)
        r = random.randint(width // 15, width // 5)
        draw.ellipse((x - r, y - r, x + r, y + r), fill=230) 
    cloud_mask = cloud_mask.filter(ImageFilter.GaussianBlur(radius=15))
    white_img = Image.new('RGB', img.size, (255, 255, 255))
    return Image.composite(white_img, base_img, cloud_mask).convert("RGB")

@st.cache_data
def apply_diabetic_retinopathy(img):
    img_copy = img.copy()
    mask = Image.new('L', img.size, 0)
    draw = ImageDraw.Draw(mask)
    width, height = img.size
    random.seed(42) 
    for _ in range(30): 
        x = random.randint(0, width)
        y = random.randint(0, height)
        r = random.randint(15, min(width, height) // 6) 
        draw.ellipse((x - r, y - r, x + r, y + r), fill=255)
    mask = mask.filter(ImageFilter.GaussianBlur(radius=10))
    black_img = Image.new('RGB', img.size, (0, 0, 0))
    return Image.composite(black_img, img_copy, mask).convert("RGB")

# ==========================================
# MAIN APPLICATION LOGIC
# ==========================================

if uploaded_file is not None:
    original_image = Image.open(uploaded_file).convert("RGB")
else:
    try:
        original_image = Image.open("sample_image.jpg").convert("RGB")
    except FileNotFoundError:
        st.error("Please place 'sample_image.jpg' in the folder or upload an image!")
        st.stop()

st.header("Medical Eye Conditions")
st.markdown("<p style='text-align: center;'>Drag the sliders below to compare normal vision with different visual impairments.</p><br>", unsafe_allow_html=True)

conditions = [
    ("Glaucoma", apply_glaucoma),
    ("Macular Degeneration", apply_macular_degeneration),
    ("Achromatopsia", apply_achromatopsia),
    ("Cataracts", apply_cataracts),
    ("Diabetic Retinopathy", apply_diabetic_retinopathy),
    ("Low Vision", apply_low_vision)
]

descriptions = {
    "Glaucoma": "<b>The Condition:</b> Damages the optic nerve, often caused by high pressure. Typically leads to loss of peripheral vision.<br><br><b>What's in the Image:</b> A 'tunnel vision' effect where the center remains clear but edges are darkened.",
    "Macular Degeneration": "<b>The Condition:</b> Deterioration of the center of the retina. Makes reading and recognizing faces very difficult.<br><br><b>What's in the Image:</b> A dark, blurry cloud is applied directly over the center.",
    "Achromatopsia": "<b>The Condition:</b> A rare disorder where a person has a partial or total absence of color vision.<br><br><b>What's in the Image:</b> All color data is removed, resulting in a grayscale scene.",
    "Cataracts": "<b>The Condition:</b> Clouding of the lens, similar to looking through a frosted window.<br><br><b>What's in the Image:</b> Sharp background with cloudy, solid white splotches.",
    "Diabetic Retinopathy": "<b>The Condition:</b> Damage to retinal blood vessels due to diabetes. Causes dark spots or 'floaters'.<br><br><b>What's in the Image:</b> Random, solid dark splotches obscuring patches of view.",
    "Low Vision": "<b>The Condition:</b> Significant impairment that cannot be fully corrected, causing loss of sharpness.<br><br><b>What's in the Image:</b> Moderate blur and reduced brightness across the entire view."
}

# Grid Layout
col1, col2, col3 = st.columns(3, gap="large")
cols = [col1, col2, col3, col1, col2, col3]

for i, (name, func) in enumerate(conditions):
    with cols[i]:
        st.markdown(f"<div class='centered-content'><h3>{name}</h3>", unsafe_allow_html=True)
        # We let the width be responsive to the column container
        image_comparison(original_image, func(original_image), label1="Normal", label2=name)
        st.markdown(f"<div style='font-size: 1.1em; margin-top: 5px;'>{descriptions[name]}</div></div>", unsafe_allow_html=True)
